services:
  database:
    image: postgres:15
    container_name: mercaduca_database
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contra
      POSTGRES_DB: mercaduca_db
    volumes:
      - database_data:/var/lib/postgresql/data
     # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mercaduca_network

  backend:
    build: ./backend
    container_name: mercaduca_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: usuario
      DB_PASS: contra
      DB_NAME: mercaduca_db
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mercaduca_network
    command: npm start
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    container_name: mercaduca_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mercaduca_network
    command: npm run dev

volumes:
  database_data:

networks:
  mercaduca_network:
    driver: bridge
